Id: LerianStudio.mdz
Name: Mdz CLI
Publisher: Lerian Studio
Version: 0.5.9
License: MIT
InstallerType: exe
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/maxwelbm/mdz/releases/download/v0.5.9/mdz_0.5.9_windows_amd64.exe
    InstallerSha256: bcbcc5c312f0205701def9f09f04c539c58e0006a0b2161b3c4497451b38f057
Description: |
  Mdz CLI is a powerful command-line tool designed to manage APIs and services from Lerian Studio's ledger system.
Homepage: https://github.com/maxwelbm/mdz
